// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDppmdwJ1AUOyjX7jXx9fQ_0R6KeJXM3uM',
    appId: '1:1018375867888:web:de48f1749d0ccb8e23e135',
    messagingSenderId: '1018375867888',
    projectId: 'fiesta-5426e',
    authDomain: 'fiesta-5426e.firebaseapp.com',
    storageBucket: 'fiesta-5426e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa45CFx_bTCQ2E-FgcQmr3SmXV-WQKls0',
    appId: '1:1018375867888:android:2a5a7d1ff0b3cdc423e135',
    messagingSenderId: '1018375867888',
    projectId: 'fiesta-5426e',
    storageBucket: 'fiesta-5426e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4weP-1VNZ0eUWjObQSOvQvD6fTIV-lpk',
    appId: '1:1018375867888:ios:6cfbccbd2715b09823e135',
    messagingSenderId: '1018375867888',
    projectId: 'fiesta-5426e',
    storageBucket: 'fiesta-5426e.appspot.com',
    iosBundleId: 'com.example.flavourFiesta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4weP-1VNZ0eUWjObQSOvQvD6fTIV-lpk',
    appId: '1:1018375867888:ios:4cb9d339f9256dcf23e135',
    messagingSenderId: '1018375867888',
    projectId: 'fiesta-5426e',
    storageBucket: 'fiesta-5426e.appspot.com',
    iosBundleId: 'com.example.flavourFiesta.RunnerTests',
  );
}
